name: commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  gocommit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gocommit
        run: |
          git config --local user.name "hellolin-oi"
          git config --local user.email "hellolinoi@outlook.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m ":)"
          git push
